Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"
  config.vm.network "private_network", ip: "192.168.10.197"
  # config.hostsupdater.aliases = ["development.local"]
  config.vm.synced_folder ".", "/home/vagrant/code"
  config.vm.provision "shell", path: "environment/provision.sh"

end
